name: Devsecops workflow for Revision Day1
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the output of the command
        run: ifconfig >> ifconfig.json
      - name: Uplaod the output file
        uses: actions/upload-artifact@v2
        with:
          name: ifconfig Output
          path: ifconfig.json
        if: always()


  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Echo the output of command in test phase
        run: echo "this is test"
      - name: Download the output file
        uses: actions/download-artifact@v2
        with:
          name: ifconfig Output