name: Devsecops workflow for Revision Day1
on: [push]
jobs:
  build:
    runs-on: [ubuntu-latest,windows-latest]
    steps:
      - name: Print the output of the command
        run: ifconfig >> ifconfig.json
      - name: Upload the output file
        uses: actions/upload-artifact@v2
        with:
          name: ifconfig Output
          path: ifconfig.json
        if: always()
        
      - name: Print the output of the command
        run: ipconfig >> ipconfig_windows.txt
      - name: Upload the output file for windows
        uses: actions/upload-artifact@v2
        with:
          name: Windows Ipconfig output
          path: ipconfig_windows.txt


  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Echo the output of command in test phase
        run: echo "this is test"
      - name: Download the output file
        uses: actions/download-artifact@v2
        with:
          name: [ifconfig Output,Windows Ipconfig output]


        